site_name: My Docs

theme: 
  name: 'material'
  language: 'zh'
  palette:
    - scheme: slate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.js
  - js/katex.js

plugins:
  - mathenv:
      theorem:
        enable: true
        definition: "def"
        proof_autofold: false
      tikzcd:
        enable: true
        cachefile: true
      alias:
        enable: true
        alias_list: {"key": "value", "key2": "value2"}
